services:
    menuappnested:
        class: NestedMenuBundle\Twig\NestedMenuExtension
        public: true
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    front_menu_controller:
        class: NestedMenuBundle\Service\NestedMenuService
        arguments: ['@templating', '@doctrine']
